const translations = {
    en: {
        nav_dash: "Overview",
        nav_users: "User Management",
        nav_stadiums_services: "Locations List",
        nav_prediction_hub: "Prediction Engine",
        nav_reports: "Service Management",
        nav_notif: "Alerts",
        nav_logs: "Logs",
        nav_data: "Services",
        nav_models: "Model Management",
        nav_engine: "Smart Prediction",
        nav_eval: "Model Metrics",
        nav_monitor: "System Status",
        dashboard: "Dashboard",
        logout: "Logout",
        stadium_name: "Venue Designation",
        location: "Geographic Location",
        capacity: "Operational Capacity",
        username: "Full Name",
        email: "Communication Endpoint",
        role: "Permission Schema",
        service_name: "Service Designation",
        category: "Classification",
        stadium: "Primary Venue",
        sys_status: "System Analytics",
        recent_activity: "Recent Activity Trace",
        total_users: "Total System Users",
        total_services: "Active Service Points",
        total_stadiums: "Managed Venues",
        total_predictions: "Global Predictions",
        public_audience: "Public Audience",
        btn_upload: "Ingest Dataset",
        btn_execute: "Execute Inference",
        btn_users: "Manage Identities",
        btn_broadcast: "Dispatch Alert",
        timestamp: "Trace Time",
        operator: "Identified Operator",
        action: "Executed Logic",
        status: "Final Status",
        id: "Unique Identifier",
        accuracy: "Model Precision",
        opt_visitor: "Visitor Profile",
        opt_staff: "Staff / Manager",
        opt_dev: "Data Engineer",
        opt_admin: "System Root",
        opt_restaurant: "Restaurant Point",
        opt_cafe: "Cafe / Lounge",
        opt_all: "Global Broadcast",
        password: "Access Token",
        db_status: "Database Health",
        model_status: "ML Engine Health",
        step1: "Data Ingestion",
        step2: "Schema Validation",
        step3: "Feature Refresh",
        step4: "Model Execution",
        step5: "Matrix Mapping",
        step6: "Global Storage",
        step7: "Final Publication",
        batch_id: "Batch Identifier",
        init_time: "Initialization Time",
        phase: "Process Phase",
        rec_count: "Processed Records",
        audit: "Audit Action",
        db_health: "Service Database Health",
        sys_autopilot: "System Monitor [Autopilot]",
        btn_delete: "Delete Record",
        dashboard_title: "Command Center",
        dashboard_desc: "Live AI intelligence and analytics.",
        sys_live: "LIVE SYSTEM ACTIVE",
        velocity_trend: "Crowd Trend",
        intel_feed: "Live Updates",
        autopilot_msg: "Autopilot active.",
        confidence_range: "Confidence Range",
        demand_dist: "Crowd Density",
        crowd_pressure_zones: "CROWD PRESSURE ZONES",
        "Kingdom Arena": "Kingdom Arena",
        "Al-Awwal Park": "Al-Awwal Park",
        "King Fahd Stadium": "King Fahd Stadium",
        "Prince Faisal Arena": "Prince Faisal Arena",
        activity_log: "Activity Log",
        sys_node: "System Event",
        forecast_badge: "24H FORECAST",
        sync_badge: "REAL-TIME",
        // Manager Module
        manager_portal: "Staff Portal",
        nav_input: "Update Data",
        nav_predictions: "Crowd Status",
        total_assigned: "Total Managed Units",
        active_services: "Active Services",
        today_data: "Daily Data Updates",
        last_prediction: "Last AI Forecast",
        quick_actions: "Quick Actions",
        add_new_service: "Add New Service",
        update_ops_data: "Update Data",
        view_predictions: "Live Forecasts",
        service_status_panel: "Service Status",
        live_ops: "LIVE DATA",
        last_updated: "Last Updated",
        service_registry: "Service Registry",
        total_managed: "Total Services",
        add_service: "Add Service",
        location_desc: "Precise Geographic Description",
        btn_create: "Create Service",
        telemetry_ingestion: "System Data Input",
        data_input_desc: "Submit real-time service metrics to calibrate the prediction engine. High-fidelity data ensures optimal group guidance.",
        selection_service: "Select Service",
        current_occupancy: "Current Unit Occupancy",
        status_broadcast: "Status Broadcast",
        btn_ingest: "Submit Data",
        integrity_check: "System Integrity Protocol",
        rule1: "Waiting time must remain within operational bounds (0-300 min).",
        rule2: "Occupancy metrics cannot exceed established unit capacity.",
        rule3: "All submissions are archived in the System Audit Repository.",
        prediction_stream: "Live Predictions",
        filter_stadium: "Venue Scope",
        filter_service: "Select Service",
        crowd_level: "Predicted Demand Intensity",
        exp_waiting: "Expected Wait Horizon",
        no_data: "No predictive telemetry available for current filter.",
        // Developer Module
        dev_portal: "Developer Console",
        cpu_util: "Processor Utilization",
        ram_util: "Memory Allocation",
        total_nodes: "Active Services",
        model_readiness: "Model Status",
        resync_engine: "Restart Engine",
        recent_audit: "Recent Logs",
        accuracy_metrics: "Accuracy Metrics",
        st_name: "Service Name",
        visitor_count: "Visitor Count",
        ticket_count: "Ticket Count",
        model_name: "Model Name",
        loaded_at: "Loaded At",
        notes: "Notes",
        hour: "Hour",
        // Status Dynamics
        READY: "Ready",
        CONNECTED: "Connected",
        FAILED: "Failed",
        ERROR: "Error",
        ACTIVE: "Active",
        AVAILABLE: "Available",
        BUSY: "Busy",
        CLOSED: "Closed",
        OPEN: "Open",
        LOW: "Low",
        MEDIUM: "Medium",
        HIGH: "High",
        CRITICAL: "Critical",
        // Landing & Login Portal
        hero_tag: "Next-Gen Operations",
        hero_title: "CROWDCAST 2034",
        hero_desc: "The unified command center for predictive crowd intelligence, operational governance, and real-time strategic communication.",
        visitor_title: "Visitor",
        visitor_desc: "Navigate match day with real-time AI guidance. Avoid congestion and reach your seat with high efficiency.",
        staff_title: "Manager",
        staff_desc: "Operational oversight and resource optimization. Manage your sector using live predictive demand analytics.",
        dev_title: "Developer",
        dev_desc: "Model governance and strategic communication tracing. Monitor system health and neural integration metrics.",
        admin_title: "System Administrator",
        admin_desc: "Strategic command and control. Full system orchestration and real-time operational oversight.",
        btn_get_started: "Start Now",
        btn_access: "Let's Start",
        btn_explore: "Explore Traces",
        btn_enter: "Enter Command Center",
        login_gateway: "Strategic Access Gateway",
        login_desc: "Secure authentication for CROWDCAST 2034 ecosystem.",
        label_email: "Email Address",
        label_pass: "Password",
        password_hint: "Must be at least 8 characters long and contain both letters and numbers.",
        btn_auth: "Authenticate Session",
        no_account: "No system identity?",
        explore_path: "Explore Trajectories",
        welcome_msg: "Welcome to CrowdCast 2034",
        visitor_fan: "Visitor / Fan",
        plan_day: "Optimize your match day experience.",
        staff_manager: "Manager / Staff",
        manage_predict: "Manage services & demand.",
        model_gov: "Governance & Traces.",
        sys_control: "Full Control.",
        search_services: "Search Services",
        btn_ingest: "Ingest Record",
        visitor_search: "Quick Search",
        stadium_scope: "Select Stadium",
        service_focus: "Select Facility",
        select_venue: "Target Venue",
        select_unit: "Target Service Unit",
        btn_search: "Find Best Time",
        date: "Date of Visit",
        hour: "Expected Time (Hour)",
        p_stadium: "Choose event stadium",
        p_service: "Choose restaurant or gate",
        no_services: "No facilities available here",
        signup_title: "Fan Enrollment",
        signup_desc: "Create your global fan identity for CrowdCast 2034.",
        btn_signup: "Register Account",
        signup_staff_title: "Staff Enrollment",
        signup_staff_desc: "Join the 2034 operational force and manage peak crowds.",
        signup_dev_title: "Developer Onboarding",
        signup_dev_desc: "Connect to the core neural architecture and govern the models.",
        nav_search: "Quick Search",
        stadium_pulse: "Live Stadium Status",
        results_title: "Prediction Results",
        loading_telemetry: "Calculating Crowds...",
        btn_access: "Let's Go",
        have_account: "Already enrolled?",
        sys_live: "Real-time AI Active",
        btn_buy: "Buy Entry Ticket",
        expected_visitors: "Expected Visitors",
        demand: "Demand",
        destination: "Destination",
        at: "at",
        recommendation_title: "Smart Recommendation",
        syncing_telemetry: "Syncing Unit Telemetry...",
        no_localized_services: "No localized services available",
        rec_better_time: "We recommend visiting at {hour}:00 for fewer crowds (Est. {visitors} visitors).",
        rec_optimal: "You selected the optimal time with the lowest expected crowds."
    },
    ar: {
        nav_dash: "نظرة عامة",
        nav_users: "إدارة المستخدمين",
        nav_stadiums_services: "قائمة المواقع",
        nav_prediction_hub: "محرك التنبؤات",
        nav_reports: "إدارة الخدمات",
        nav_notif: "التنبيهات",
        nav_logs: "سجل الأحداث",
        nav_data: "إدارة الخدمات",
        nav_models: "إدارة النماذج",
        nav_engine: "التنبؤ الذكي",
        nav_eval: "دقة النماذج",
        nav_monitor: "حالة النظام",
        dashboard: "لوحة التحكم",
        logout: "تسجيل الخروج",
        stadium_name: "مسمى الملعب",
        location: "الموقع الجغرافي",
        capacity: "السعة التشغيلية",
        username: "الاسم الكامل",
        email: "البريد الإلكتروني",
        role: "مخطط الصلاحيات",
        service_name: "مسمى الخدمة",
        category: "التصنيف النوعي",
        stadium: "الملعب الرئيسي",
        sys_status: "تحليلات النظام",
        recent_activity: "تتبع النشاط الأخير",
        total_users: "إجمالي مستخدمي النظام",
        total_services: "نقاط الخدمة النشطة",
        total_stadiums: "الملاعب المدارة",
        total_predictions: "إجمالي التوقعات",
        public_audience: "إجمالي المشجعين",
        btn_upload: "استيراد الداتا",
        btn_execute: "تنفيذ التنبؤ",
        btn_users: "إدارة الهويات",
        btn_broadcast: "بث التنبيه",
        timestamp: "وقت التتبع",
        operator: "المشغل المعرف",
        action: "المنطق المنفذ",
        status: "الحالة النهائية",
        id: "المعرف الفريد",
        accuracy: "دقة النموذج",
        opt_visitor: "بروفايل زائر",
        opt_staff: "موظف / مدير",
        opt_dev: "مهندس بيانات",
        opt_admin: "جذر النظام",
        opt_restaurant: "نقطة مطعم",
        opt_cafe: "مقهى / لاونج",
        opt_all: "بث عالمي",
        password: "رمز الدخول",
        db_status: "صحة قاعدة البيانات",
        model_status: "صحة محرك الذكاء",
        step1: "استيراد البيانات",
        step2: "فحص المخطط",
        step3: "تحديث الميزات",
        step4: "تنفيذ النموذج",
        step5: "رسم المصفوفة",
        step6: "التخزين العالمي",
        step7: "النشر النهائي",
        batch_id: "معرف الدفعة",
        init_time: "وقت البدء",
        phase: "مرحلة المعالجة",
        rec_count: "عدد السجلات",
        audit: "إجراء التدقيق",
        db_health: "صحة قاعدة بيانات الخدمة",
        sys_autopilot: "مراقب النظام [تشغيل آلي]",
        btn_delete: "حذف السجل",
        dashboard_title: "مركز القيادة",
        dashboard_desc: "تحليلات الذكاء الاصطناعي والبيانات المباشرة.",
        sys_live: "نظام البث المباشر نشط",
        velocity_trend: "اتجاه الحشود",
        intel_feed: "التحديثات اللحظية",
        autopilot_msg: "الطيار الآلي يعمل.",
        confidence_range: "دقة التنبؤ",
        demand_dist: "مستويات الازدحام",
        crowd_pressure_zones: "مناطق ضغط الحشود",
        "Kingdom Arena": "المملكة أرينا",
        "Al-Awwal Park": "الأول بارك",
        "King Fahd Stadium": "استاد الملك فهد",
        "Prince Faisal Arena": "استاد الأمير فيصل",
        activity_log: "سجل النشاط",
        sys_node: "حدث النظام",
        forecast_badge: "توقعات 24 ساعة",
        sync_badge: "مزامنة الوقت الحقيقي",
        // Manager Module
        manager_portal: "بوابة الموظف",
        nav_input: "تحديث البيانات",
        nav_predictions: "حالة الازدحام",
        total_assigned: "إجمالي الوحدات المدارة",
        active_services: "الخدمات النشطة",
        today_data: "تحديثات البيانات اليومية",
        last_prediction: "آخر توقع ذكاء اصطناعي",
        quick_actions: "الإجراءات السريعة",
        add_new_service: "إضافة خدمة جديدة",
        update_ops_data: "تحديث بيانات النظام",
        view_predictions: "التوقعات المباشرة",
        service_status_panel: "مراقبة الخدمات",
        live_ops: "العمليات المباشرة",
        last_updated: "آخر تحديث",
        service_registry: "سجل الخدمات",
        total_managed: "إجمالي الخدمات",
        add_service: "إضافة خدمة",
        location_desc: "وصف الموقع الجغرافي الدقيق",
        btn_create: "إنشاء خدمة",
        telemetry_ingestion: "تحديث بيانات النظام",
        data_input_desc: "أرسل مقاييس الخدمة في الوقت المعاير لمحرك التنبؤ. تضمن البيانات عالية الجودة توجيه المجموعات الأمثل.",
        selection_service: "اختر الخدمة",
        current_occupancy: "إشغال الوحدة الحالي",
        status_broadcast: "حالة التوفر",
        btn_ingest: "تحديث البيانات",
        integrity_check: "بروتوكول نزاهة النظام",
        rule1: "يجب أن يبقى وقت الانتظار ضمن النطاق التشغيلي (0-300 دقيقة).",
        rule2: "لا يمكن أن تتجاوز مقاييس الإشغال سعة الوحدة المحددة.",
        rule3: "يتم أرشفة جميع المدخلات في مستودع سجلات النظام.",
        prediction_stream: "التوقعات المباشرة",
        filter_stadium: "نطاق الملعب",
        filter_service: "اختر الخدمة",
        crowd_level: "كثافة الطلب المتوقعة",
        exp_waiting: "أفق الانتظار المتوقع",
        no_data: "لا توجد بيانات توقع متاحة لهذا الفلتر.",
        // Developer Module
        dev_portal: "بوابة المطورين",
        cpu_util: "استهلاك المعالج",
        ram_util: "تخصيص الذاكرة",
        total_nodes: "الخدمات النشطة",
        model_readiness: "حالة النماذج",
        resync_engine: "إعادة تشغيل المحرك",
        recent_audit: "السجلات الأخيرة",
        accuracy_metrics: "مقاييس الدقة",
        st_name: "اسم الخدمة",
        visitor_count: "عدد الزوار",
        ticket_count: "عدد التذاكر",
        model_name: "اسم النموذج",
        loaded_at: "تاريخ التحديث",
        notes: "ملاحظات",
        hour: "الوقت",
        // Status Dynamics
        READY: "جاهز",
        CONNECTED: "متصل",
        FAILED: "فشل",
        ERROR: "خطأ",
        ACTIVE: "نشط",
        AVAILABLE: "متاح",
        BUSY: "مشغول",
        CLOSED: "مغلق",
        OPEN: "مفتوح",
        LOW: "منخفض",
        MEDIUM: "متوسط",
        HIGH: "مرتفع",
        CRITICAL: "حرج",
        // Landing & Login Portal
        hero_tag: "عمليات الجيل القادم",
        hero_title: "كراود كاست 2034",
        hero_desc: "مركز القيادة الموحد لاستخبارات الحشود التنبؤية، الحوكمة التشغيلية، والاتصال الاستراتيجي اللحظي.",
        visitor_title: "زائر",
        visitor_desc: "تصفح يوم المباراة بإرشادات الذكاء الاصطناعي اللحظية. تجنب الازدحام وصل لمقعدك بكفاءة عالية.",
        staff_title: " مدير",
        staff_desc: "الإشراف التشغيلي وتحسين الموارد. أدر قطاعك باستخدام تحليلات الطلب التنبؤية الحية.",
        dev_title: "مطور ",
        dev_desc: "حوكمة النماذج وتتبع الاتصال الاستراتيجي. راقب صحة النظام ومقاييس التكامل العصبي.",
        admin_title: "مدير النظام",
        admin_desc: "القيادة والتحكم الاستراتيجي. تنظيم النظام بالكامل والإشراف التشغيلي في الوقت الفعلي.",
        btn_get_started: "ابدأ الآن",
        btn_access: "دخول الكونسول",
        btn_explore: "استكشاف التتبع",
        btn_enter: "دخول مركز القيادة",
        login_gateway: "بوابة الدخول السريع",
        login_desc: "تسجيل دخول آمن لمنصة المشجعين لبطولة 2034.",
        label_email: "البريد الإلكتروني",
        label_pass: "كلمة السر",
        password_hint: "يجب أن تتكون من 8 خانات على الأقل وتحتوي على أحرف وأرقام معاً لحماية حسابك.",
        btn_auth: "تسجيل الدخول",
        no_account: "ليس لديك حساب للبطولة؟",
        explore_path: "اكتشف الفعاليات",
        welcome_msg: "أهلاً بك في منصة المشجعين",
        visitor_fan: "زائر / مشجع",
        plan_day: "خطط لتجربتك في كأس العالم وتجنب الزحام بكل سهولة.",
        staff_manager: "مدير / موظف",
        manage_predict: "إدارة الخدمات والطلب.",
        model_gov: "الحوكمة والتتبع.",
        sys_control: "تحكم كامل.",
        search_services: "البحث السريع",
        btn_ingest: "حقن السجل",
        signup_title: "تسجيل المشجعين",
        signup_desc: "أنشئ حسابك وتجنب طوابير الانتظار في كأس العالم 2034.",
        btn_signup: "تسجيل حساب جديد",
        signup_staff_title: "تسجيل الكوادر التشغيلية",
        signup_staff_desc: "انضم إلى القوة التنظيمية لبطولة 2034 وقم بإدارة الزحام.",
        signup_dev_title: "تسجيل مطوري الأنظمة",
        signup_dev_desc: "اتصل بالمعمارية العصبية الأساسية وقم بحوكمة النماذج التنبؤية.",
        nav_search: "البحث السريع",
        stadium_pulse: "حالة الملاعب المباشرة",
        results_title: "تفاصيل توقع الزحام",
        loading_telemetry: "جاري حساب الازدحام بالذكاء الاصطناعي...",
        btn_access: "دعنا نبدأ",
        have_account: "هل لديك حساب بالفعل؟",
        sys_live: "مربوط بالذكاء الاصطناعي الحي",
        visitor_search: "الاستعلام السريع",
        stadium_scope: "اختر الملعب",
        service_focus: "اختر المرفق (مطعم / بوابة)",
        btn_search: "عرض أوقات الزحام",
        date: "تاريخ الزيارة",
        hour: "وقت الزيارة (بالساعة)",
        p_stadium: "حدد ملعب المباراة",
        p_service: "اختر المطعم أو المرفق",
        no_services: "لا توجد مرافق مسجلة حالياً",
        btn_buy: "شراء تذكرة الدخول",
        expected_visitors: "توقعات الزوار",
        demand: "مستوى الطلب",
        destination: "الوجهة",
        at: "في",
        recommendation_title: "توصية ذكية",
        syncing_telemetry: "جاري مزامنة بيانات المرفق...",
        no_localized_services: "لا توجد مرافق محلية متاحة",
        rec_better_time: "نوصي بالزيارة في الساعة {hour}:00 لتجنب الزحام (توقع {visitors} زائر).",
        rec_optimal: "لقد اخترت الوقت المثالي مع أقل توقع للازدحام."
    }
};

function toggleLanguage() {
    const savedLang = localStorage.getItem('crowdcast_lang') || 'en';
    const newLang = savedLang === 'en' ? 'ar' : 'en';
    localStorage.setItem('crowdcast_lang', newLang);
    applyLanguage(newLang);
}

function applyLanguage(lang) {
    const body = document.getElementById('body-root');
    const html = document.getElementById('html-root');
    const langLabel = document.getElementById('lang-label');
    
    const isAr = lang === 'ar';
    
    // 1. Directional Logic
    if (html) html.setAttribute('lang', lang);
    if (body) {
        body.setAttribute('dir', isAr ? 'rtl' : 'ltr');
        body.classList.toggle('rtl-mode', isAr);
    }
    
    // 2. Button Label (Shows opposite)
    if (langLabel) langLabel.innerText = isAr ? 'English' : 'عربي';

    // 3. Batch Translation (Static)
    document.querySelectorAll('[data-t]').forEach(el => {
        const key = el.getAttribute('data-t');
        if (translations[lang] && translations[lang][key]) {
            if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
                el.placeholder = translations[lang][key];
            } else {
                el.innerText = translations[lang][key];
            }
        }
    });

    // 4. Dynamic Data Mapping (Statuses, Levels, Roles)
    document.querySelectorAll('[data-t-dynamic]').forEach(el => {
        const rawValue = el.getAttribute('data-t-dynamic').trim();
        // Check if raw value exists in our dictionary
        if (translations[lang] && translations[lang][rawValue]) {
            el.innerText = translations[lang][rawValue];
        } else {
            // Check if it's a role or common status
            const upperVal = rawValue.toUpperCase();
            if (translations[lang][upperVal]) {
                el.innerText = translations[lang][upperVal];
            }
        }
    });

    // 5. Placeholder Specific Mapping
    document.querySelectorAll('[data-t-p]').forEach(el => {
        const key = el.getAttribute('data-t-p');
        if (translations[lang] && translations[lang][key]) {
            el.placeholder = translations[lang][key];
        }
    });

    // 6. Parameterized Translations
    document.querySelectorAll('[data-t-params]').forEach(el => {
        const key = el.getAttribute('data-t-key');
        const paramsRaw = el.getAttribute('data-t-params');
        if (translations[lang] && translations[lang][key]) {
            let str = translations[lang][key];
            try {
                const params = JSON.parse(paramsRaw);
                Object.keys(params).forEach(p => {
                    str = str.replace(`{${p}}`, params[p]);
                });
                el.innerText = str;
            } catch (e) { console.error("Translation param error", e); }
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('crowdcast_lang') || 'en';
    applyLanguage(savedLang);
});
